### ISSUE TITLE
Navigator cannot select the Widget

### ISSUE THREAD

**Issue by CHTUZKI** [terjeio/Display-libraries#2]
HI.

I used this library to create a page：

![image](https://user-images.githubusercontent.com/42321222/224079737-c76f0966-4ded-4b3f-86ef-d0acc9a71fb1.png)

I can't use Navigator to switch between these three text boxes, and I can't select buttons.

When the canvas enters, I can see the cursor of text box 1 blinking. Does the Navigator of this library support horizontal layout，I see that the menu of your tivac DRO project uses vertical layout, and the Navigator works normally.

I don't know what the function of `event ->claimed` is and when it needs to be used.

Thank you.~

**Comment by terjeio** [comment]
> Does the Navigator of this library support horizontal layout

It has been a while since I worked on this library so not sure... The navigator only moves the "mouse" pointer in one direction - vertically, so without code modifying the horizontal pointer position horizontal layout is not supported.
However, if I am not mistaken, if you add a  handler for the _EventPointerLeave_ event to the widget you can force entry to the next (or previous) widget by calling `UILibApplyEnter()` with the widget handle. This repositions the "mouse" pointer to the center of that widget.

The internal caretEdit() function uses a similar trick to[ implement tabbing based on keypresses](https://github.com/terjeio/Display-libraries/blob/c497991b2773a8c77c366bd8e1fdea227b06e748/UILib/uilib.c#L464-L474).

> I don't know what the function of event ->claimed is and when it needs to be used.

Events are posted to the widget hierarchy in an upward fashion with the screen beeing the top. Claiming an event stops the event from beeing fired for higher up widgets and eventually reaching the default handler.
Here is an example of how I prevent the last button in a column of buttons from losing focus on pointer leave downwards by claiming the _EventPointerLeave_ event:

```
static void handlerButtonSetup (Widget *self, Event *event)
{
	switch(event->reason) {

		case EventPointerUp:
		    event->claimed = true;
		    UILibWidgetDeselect(self);
			CONFIGShowCanvas();
			break;

		case EventPointerLeave:
			event->claimed = event->y > self->yMax;
			break;
	}
}
```

**Comment by CHTUZKI** [comment]
Thank you for your answer.
Yes. I found that if the Y coordinates of three buttons are the same, the program doesn't know which direction to look for the next button。

```
if(chg >= event->event.tabNav) 
{
      if((nextWidget = widgetGetNext(widget, WidgetAll, false)))
              event->event.pos = widgetGetCPos(nextWidget);
} 
else if(chg <= -event->event.tabNav) 
{
       if((nextWidget = widgetGetPrev(widget, WidgetAll, false)))
               event->event.pos = widgetGetCPos(nextWidget);
}
```
The above code cannot be executed well.

I created a button at position (0, 0) and then hidden it. The problem was solved.
